version: "3.4"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=db
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=username
  app:
    build: 
      context: app/
    volumes:
      - ./app/:/code/
    command: sh -c "./scripts/run.sh"
    ports:
      - "80:80"
    depends_on:
      - db
    restart: on-failure

