version: "3.4"
   
services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: url_api
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
  app:
    build: 
      context: app/
    volumes:
      - ./app/:/code/
    command: sh -c "./scripts/run.sh"
    ports:
      - "5000:5000"
    depends_on:
      - db
    restart: on-failure

